language: go

os: osx

# NB: Travis-CI does have support for an os list in the main .travis.yml
# and this would be preferrable, but they are currently under capacity
# on osx slaves and not accepting new users:
#   http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
language: objective-c

# TODO: support building/testing with both golang and gccgo?
go:
  - 1.4

matrix:
  fast_finish: true

before_install:
  - brew update
  - brew outdated gettext || brew upgrade gettext
  - brew link gettext --force

install:
  - go get -v github.com/dvbportal/osx-lxd
  - cd $GOPATH/src/github.com/dvbportal/osx-lxd/lxd
  - go get -v -d ./...

script: "sudo -E env PATH=$PATH make check"
notifications:
