language: go

os: osx

# NB: Travis-CI does have support for an os list in the main .travis.yml
# and this would be preferrable, but they are currently under capacity
# on osx slaves and not accepting new users:
#   http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
language: objective-c

go:
  - 1.4

matrix:
  fast_finish: true

before_install:
  - brew update
  - brew install gettext
  - brew link gettext --force

install:
  - mkdir ~/go
  - export GOPATH=~/go
  - go get -v github.com/dvbportal/osx-lxd
  - cd $GOPATH/src/github.com/dvbportal/osx-lxd/lxc
  - go get -v -d ./...

script:
notifications:
