language: go

# TODO: support building/testing with both golang and gccgo?
go:
  - 1.4
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - brew update
  - brew outdated gettext || brew upgrade gettext
  - brew link gettext --force

install:
  - go get -v github.com/dvbportal/osx-lxd
  - cd $GOPATH/src/github.com/dvbportal/osx-lxd/lxd
  - go get -v -d ./...

script: "sudo -E env PATH=$PATH make check"
notifications:
